# Site settings
title: Chipping away
header-img: img/home-bg.png
email: marcus.havranek@havranek.co.at
copyright_name: mhav
description: > # this means to ignore newlines until "baseurl:"
  A very slow and long journey in Rails development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mhav
learn_profile: mhav
email_username: marcus.havranek@havranek.co.at

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
